language: python
python:
  - "3.6"
addons:
  apt:
    packages:
      - openjdk-8-jre
install:
  - pip install html5validator
script:
  - html5validator --root .
notifications:
  slack: exeum-foundation:N5NC7XlSG6BlY85rF3aILVG6
